### ISSUE TITLE
Build fails without CUDA runtime in pytorch 1.3

### ISSUE THREAD

**Issue by vladserkoff** [microsoft/pytorch_od#11]
@dashesy, hello again!
Maybe somewhat related to #1, I'm not sure.
With pytorch 1.3 I am unable to build cuda extension without cuda runtime.
I'm building inside docker, `pytorch/pytorch:1.3-cuda10.1-cudnn7-devel` specifically, but the build fails with an error that nvidia driver could not be found. The full traceback is more than a thousand lines long, I provide the python traceback in the bottom.
When I run the container with `--runtime=nvidia` the build ends successfully.

<details>
<summary>Python traceback</summary>

```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-1xpkr4i_/setup.py", line 89, in <module>
      'Topic :: Software Development',
    File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 353, in build_extensions
      build_ext.build_extensions(self)
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
      _build_ext.build_extension(self, ext)
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
      depends=ext.depends)
    File "/opt/conda/lib/python3.6/distutils/ccompiler.py", line 574, in compile
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 269, in unix_wrap_compile
      "'-fPIC'"] + cflags + _get_cuda_arch_flags(cflags)
    File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 977, in _get_cuda_arch_flags
      capability = torch.cuda.get_device_capability()
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 328, in get_device_capability
      prop = get_device_properties(device)
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 334, in get_device_properties
      init()  # will define _get_device_properties and _CudaDeviceProperties
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 164, in init
      _lazy_init()
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 192, in _lazy_init
      _check_driver()
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 102, in _check_driver
      http://www.nvidia.com/Download/index.aspx""")
  AssertionError:
  Found no NVIDIA driver on your system. Please check that you
  have an NVIDIA GPU and installed a driver from
  http://www.nvidia.com/Download/index.aspx
  ----------------------------------------
  ERROR: Failed building wheel for mictorch
  Running setup.py clean for mictorch
Failed to build mictorch
```
</details>

**Comment by dashesy** [comment]
Please open an issue for PyTorch. `pytorch/pytorch:1.3-cuda10.1-cudnn7-devel` should be able to build the cuda code, even if there is no cuda runtime. `_get_cuda_arch_flags` is trying to build for the current device, but there should be an option to build for some common set of hardware and avoid looking for GPU device.
